# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 로봇 제작을 위한 지식공간
description: > # this means to ignore newlines until "baseurl:"
  This blog was designed to deliver the knowledge to people who want to make private Robots <br>
  jekyll theme을 입힌 블로그 
baseurl: ""
url: "https://lsirikh.github.io"
permalink: /:year/:month/:day/:title
repository: 
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/lsirikh"
user: "이기호(Kiho Lee)"
user_email: "lsirikh@naver.com"
contact_url: "https://memaker.co.kr"
google_tracking_id: ""
google_site_verification: ""
disqus_shortname: "lsirikh-github-io"


# Blog Layout settings

categories: ROS C C++ GIT Firmware Python AI Mathematics
tags: 

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true



#To set up your environment to develop this theme, 
# clone/fork the repo and run bundle install.

#To test your theme, run bundle exec jekyll serve
# and open your browser at http://localhost:4000/. 
# This starts a Jekyll server using your theme. 
# Add pages, documents, data, etc. like normal to 
# test your theme's contents. As you make 
# modifications to your theme and to your content, 
# your site will regenerate and you should see the 
# changes in the browser after a refresh, just like 
# normal.
